### ISSUE TITLE
@uiw/react-code-preview@1.10.0 安装失败

### ISSUE THREAD

**Issue by kuhami** [uiwjs/react-baidu-map#1]
@uiw/react-code-preview@1.10.0 安装失败，对应的 node 和 npm 的版本是多少？

**Comment by jaywcjlove** [comment]
@kuhami 报错内容是什么

**Comment by jaywcjlove** [comment]
@kuhami 目前我的版本较高，一般情况应该 `node 8+` 以上吧

```bash
▶ node -v
v12.10.0
▶ npm -v
6.11.3
```

**Comment by kuhami** [comment]
> @kuhami 报错内容是什么

执行  npm install @uiw/react-code-preview

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mwbyd/.npm/_logs/2019-11-20T09_01_26_946Z-debug.log

**Comment by jaywcjlove** [comment]
@kuhami 帮你搜索了一下，网上建议升级 `npm` 来解决这个问题。

```bash
npm install -g npm #  升级到最新版
```
