### ISSUE TITLE
BMap.Autocomplete 缺少 addEventListener方法

### ISSUE THREAD

**Issue by amin168** [uiwjs/react-baidu-map#10]
http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference.html#a7b44

![image](https://user-images.githubusercontent.com/10808093/76695693-60f8ed80-66bd-11ea-83d6-21e10a7387c4.png)
![image](https://user-images.githubusercontent.com/10808093/76695707-a0bfd500-66bd-11ea-8885-f08c5eec9190.png)

**Comment by jaywcjlove** [comment]
@amin168  你这个地方不是这么用的吧

```js
const autocomplete = new BMap.Autocomplete(autocompleteOption)
autocomplete.onconfirm = () => {}
autocomplete.onhighlight = () => {}
```

**Comment by amin168** [comment]
@jaywcjlove 这里经过确认，是你这种写法，谢谢你
