### ISSUE TITLE
LocalSearchOptions 中 onSearchComplete 的 results 参数类型有误

### ISSUE THREAD

**Issue by amin168** [uiwjs/react-baidu-map#11]
`LocalSearchOptions` 中 `onSearchComplete` 的 `results` 参数类型应该是`LocalResult` 而不是`LocalResult[]`

![image](https://user-images.githubusercontent.com/10808093/76695993-0d889e80-66c1-11ea-9e44-f003ac07be87.png)

![image](https://user-images.githubusercontent.com/10808093/76695984-ef22a300-66c0-11ea-8775-1628bc30d4b5.png)

**Comment by jaywcjlove** [comment]
@amin168 欢迎提交 PR

**Comment by jaywcjlove** [comment]
@amin168 官方文档是这么说的

> 检索完成后的回调函数。 参数：results: LocalResult或Array 如果是多关键字检索，回调函数参数返回一个LocalResult的数组，数组中的结果顺序和检索中多关键字数组中顺序一致

![image](https://user-images.githubusercontent.com/1680273/76703430-a395e680-670c-11ea-9066-ed85299829d6.png)

**Comment by jaywcjlove** [comment]
https://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference_3_0.html#a7b1

**Comment by amin168** [comment]
那我这里就自己做判断啦
