### ISSUE TITLE
用ESLint时，会出现BMap is not defined

### ISSUE THREAD

**Issue by amin168** [uiwjs/react-baidu-map#12]
![image](https://user-images.githubusercontent.com/10808093/76833263-f800a980-6865-11ea-8b81-5be08e542eea.png)

我目前的解决方法是在`.eslintrc.js`文件，做了如下设置，ESLint就不会报错了，不知道是不是我用的的问题= =
![image](https://user-images.githubusercontent.com/10808093/76833241-ef0fd800-6865-11ea-8aad-440c2186f500.png)

**Comment by jaywcjlove** [comment]
@amin168 我也是这么干的。

https://github.com/uiwjs/react-baidu-map/blob/54486c4dcb670f747b94f6a30ae5ddda41647ef7/package.json#L80-L91

其实在 `src/types/base.d.ts` 也是定义了类型

```ts
declare global {
  interface Window {
    BMap: typeof BMap;
  }
}
```

**Comment by amin168** [comment]
对，我看源码也是定义了，估计就是`ESLint`的问题咯

**Comment by simplast** [comment]
+1 用的umi，控制台也报错

**Comment by jaywcjlove** [comment]
@simplast 类型已定义，不知道你怎么玩儿的，你可以参考楼上配置ESLint 来解决问题

https://github.com/uiwjs/react-baidu-map/blob/bff63bb0d175487203e2375380f3a76e860d0552/src/types/base.d.ts#L2-L6
