### ISSUE TITLE
折线无法自动清除

### ISSUE THREAD

**Issue by ywxt** [uiwjs/react-baidu-map#121]
条件渲染，之前的折线不会清除。
(https://codesandbox.io/s/elated-rgb-ubw0o)

**Comment by jaywcjlove** [comment]
@ywxt  Upgrade `+ @uiw/react-baidu-map@1.18.4`

**Comment by ywxt** [comment]
是我的原因吗？好像还是不行。

**Comment by jaywcjlove** [comment]
@ywxt 应该可以了 `+ @uiw/react-baidu-map@1.18.5`

**Comment by ywxt** [comment]
还是不行。。。怎么回事？

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/116259130-1e528180-a7a8-11eb-84a1-1305e1c6b9ad.png)


@ywxt 官网实例测试还可以的样子

**Comment by ywxt** [comment]
是这样的，我通过一个数组map画了一系列折线，当数组更改时，之前的折线不会清除。这样叠加之后，条件控制只能使最后一次画的消失。
