### ISSUE TITLE
请问有高德地图版本的嘛？

### ISSUE THREAD

**Issue by xiaohuoni** [uiwjs/react-baidu-map#13]
看了你的Api设计，感觉很合我的胃口。
我们的项目也有高德地图的，不知道你有没有做这个？

**Comment by jaywcjlove** [comment]
@xiaohuoni 没有高德版本呢。

**Comment by jaywcjlove** [comment]
@xiaohuoni 一不小心就有了高德地图，热乎的：

- GitHub：https://github.com/uiwjs/react-amap
- Github Web: https://uiwjs.github.io/react-amap/

**Comment by xiaohuoni** [comment]
@jaywcjlove 👍
