### ISSUE TITLE
可否添加百度的第三方：鼠标绘制工具条库

### ISSUE THREAD

**Issue by amin168** [uiwjs/react-baidu-map#14]
http://lbsyun.baidu.com/index.php?title=jspopular3.0/guide/mouse2draw

http://lbsyun.baidu.com/index.php?title=jspopular3.0/openlibrary

demo：https://lbsyun.baidu.com/jsdemo.htm#f0_7

**Comment by jaywcjlove** [comment]
@amin168 你可以通过这个实例来添加第三方库 

https://github.com/uiwjs/react-baidu-map/tree/master/src/CurveLine

通过 `requireScript` 方法懒加载第三方包。

https://github.com/uiwjs/react-baidu-map/blob/master/src/CurveLine/useCurveLine.tsx#L25-L31

方法 [requireScript](https://github.com/uiwjs/react-baidu-map/blob/master/src/index.tsx#L1) 已经导出。

```js
import { requireScript } from '@uiw/react-baidu-map';

requireScript('//api.map.baidu.com/library/CurveLine/1.5/src/CurveLine.min.js').then(() => {
  if (window.BMapLib) {
    console.log(window.BMapLib);
  }
}).catch(() => {

});
```

**Comment by jaywcjlove** [comment]
@amin168 目前没有空去封装，如果你急，你可以根据实例 来个 PR 。

**Comment by amin168** [comment]
@jaywcjlove 我先自己试着封装一下，到时来个PR

**Comment by amin168** [comment]
我尝试运行`npm run doc:dev`，但报了以下的错误，是缺少了什么组件吗。

我现在封装了一点，想测试一下

![image](https://user-images.githubusercontent.com/10808093/77520996-f7e35800-6ebc-11ea-8659-62a0b1a74821.png)

我发了一封邮件给你，想叫你拿个QQ或者WeChat的联系方式ヽ(ー_ー)ノ

**Comment by jaywcjlove** [comment]
@amin168 兼容windows环境变量要使用这个包 [`cross-env`](https://www.npmjs.com/package/cross-env) 环境变量只支持 Mac OS 和 Linux 系统。

**Comment by jaywcjlove** [comment]
@amin168 你试一试。
