### ISSUE TITLE
你好，点聚合的案例有吗

### ISSUE THREAD

**Issue by xiangjiayu** [uiwjs/react-baidu-map#163]

**Comment by jaywcjlove** [comment]
@xiangjiayu 参照官方示例，来写哦， API都弄出来了。

**Comment by xiangjiayu** [comment]
ok，我按官方实例写出来了

**Comment by jaywcjlove** [comment]
@xiangjiayu 欢迎分享你的示例。

**Comment by xiangjiayu** [comment]
官方文档的实例就是把marker 集合成数组 。调用即可。new BMapLib.MarkerClusterer(map, { markers });

import React, { useState, useEffect, useRef } from 'react';
import { connect } from 'umi';
import { APILoader, useMap, useMarker, useInfoWindow, useLabel, useCircle } from '@uiw/react-baidu-map';
import { isEmpty } from 'lodash';
const MapPolymerize: React.FC<any> = (props) => {
  const point = [{longitude: 118.749463, latitude: 31.943996}]  // 经纬度接口数据获取的。可以自己mock数据
const Example = () => {
    const divElm = useRef<any>(null);

    const onLoad = (e: any) => {
      if (e && e.target) {
        if (!isEmpty(point)) {
          const markers: any = [];
          let pt = null;
          const options = [];
          point.forEach((item: any) => {
            pt = new BMap.Point(item.longitude, item.latitude);
            const orderMarker = new BMap.Marker(pt);
            markers.push(orderMarker);
            options.push({ lng: item.longitude, lat: item.latitude, count: 10 });
            // 标点添加点击事件
            orderMarker.addEventListener('click', () => {});
          });
          // 点聚合
          new BMapLib.MarkerClusterer(map, { markers });
        }
      }
    };

    const { map, setContainer } = useMap({
      center:'南京市',
      enableMapClick:true,
      zoom:16,
      enableScrollWheelZoom:true,
      onLoad,
      widget:['GeolocationControl', 'NavigationControl'],
    });

    useEffect(() => {
      if (divElm.current) {
        setContainer(divElm.current);
      }
    });

    return  <div ref={divElm} style={{ height: '100%' }} />
  };

  return (
     <div className={styles.mapWrap}>
        <APILoader {...mapConfig}>
          <Example />
        </APILoader>
      </div>
  );
}
export default connect()(MapPolymerize);

**Comment by shabishabishabishabi** [comment]
你好这个new BMapLib是自己封装的吗？现在的组件好像没有这个了
