### ISSUE TITLE
CurveLine & DrawingManager 在对话框下使用，会出现 BMap undefined

### ISSUE THREAD

**Issue by amin168** [uiwjs/react-baidu-map#17]
由于 `CurveLine & DrawingManager`  依赖 `BMap`，而我的对话框时 `show` 出来后再才会执行下面的代码，这里有两个问题出现

问题1：`CurveLine & DrawingManager`依赖的`BMap`，没有加载，所以导致`BMap undefined`，我的解决方法，如下
![image](https://user-images.githubusercontent.com/10808093/77766678-ee9fea00-707a-11ea-8058-b4c4c1d5a853.png)

问题2：由于 `BMap` 没有加载成功，所以 `BMAP_ANCHOR_TOP_RIGHT` 和 `new BMap.Size(5, 5)`，都会是`undefined`，如下图。**这个我暂时还没想到怎么解决**

![image](https://user-images.githubusercontent.com/10808093/77766205-468a2100-707a-11ea-8e8d-e0568c9effd3.png)

**Comment by jaywcjlove** [comment]
@amin168 提供完整示例

```js
import { Map, APILoader } from '@uiw/react-baidu-map';

const Demo = () => (
  <div style={{ width: '100%', height: '300px' }}>
    <APILoader akay="GTrnXa5hwXGwgQnTBG28SHBubErMKm3f">
      <Map />
    </APILoader>
  </div>
);
```

改变如下写法，`APILoader`，用于加载百度地图 `SDK` 依赖，加载完成，全局将会有 **window.BMap** 对象。

```js
import { Map, APILoader } from '@uiw/react-baidu-map';

const Example = () => {
  return (
    <>
      <Map zoom={13} center={{ lng: 121.460977, lat: 31.227906 }} />
    </>
  );
}

const Demo = () => (
  <div style={{ width: '100%', height: '300px' }}>
    <APILoader akay="GTrnXa5hwXGwgQnTBG28SHBubErMKm3f">
      <Example />
    </APILoader>
  </div>
);
```
