### ISSUE TITLE
特定的zoom会出现白色虚线，手动缩放后消失

### ISSUE THREAD

**Issue by Feafortecsy** [uiwjs/react-baidu-map#171]
环境: mac

版本: v1.18.16

出现条件: 

```
// 其他坐标没有试过，zoom在 4-4.5之间
center={{
  lng: 108.286462,
  lat: 34.138358
}}
zoom={4.2}
```

![图片示例](https://user-images.githubusercontent.com/31724313/128475528-f7fcf5d9-0a6c-42d7-a165-2b1fdb9dfb93.png)

在线示例: [白色虚线](https://codesandbox.io/s/thirsty-chaum-c86h1)

**Comment by jaywcjlove** [comment]
@Feafortecsy 你这个需求应该给百度地图提。
