### ISSUE TITLE
defaultCursor  属性不存在

### ISSUE THREAD

**Issue by dream2023** [uiwjs/react-baidu-map#202]
![image](https://user-images.githubusercontent.com/19297757/133930220-050aee25-3558-423e-bb3e-9577e2eabc17.png)

如图

**Comment by jaywcjlove** [comment]
@dream2023 Upgrade `@uiw/react-baidu-map@2.0.3`

**Comment by dream2023** [comment]
![image](https://user-images.githubusercontent.com/19297757/133954565-96d656a5-84d7-409b-9c54-b9f8391f2729.png)
![image](https://user-images.githubusercontent.com/19297757/133954580-24b8b10a-fdc6-46b0-a4ab-973a016faae8.png)

升级了，但还是没有，看了一下 `@uiw/react-baidu-map-map` 升级后还是 2.0.2，是不是这个库没有同步更新

**Comment by jaywcjlove** [comment]
@dream2023 本地测试没有问题的样子

**Comment by jaywcjlove** [comment]
https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-baidu-map-map/file/esm/index.d.ts

@dream2023

**Comment by dream2023** [comment]
我删掉依赖重新安装一下好了，直接在原来基础上升级好像不太行，不过，多谢多谢过节还在及时回复
