### ISSUE TITLE
Label 组件 style 类型定义错误

### ISSUE THREAD

**Issue by dream2023** [uiwjs/react-baidu-map#204]
错误展示如下：

![image](https://user-images.githubusercontent.com/19297757/133970530-5d8f007d-05ca-4f0f-ae87-ba775c7b7d5d.png)

style 你这边定义为了 `HTMLDivElement['style']`，但实际应该是 `React.CSSProperties`

**Comment by jaywcjlove** [comment]
@dream2023 Upgrade `@uiw/react-baidu-map@v2.0.4`

**Comment by dream2023** [comment]
大佬真的是勤奋，感谢。

这个问题有复现步骤和说明了，有空可以瞅瞅：https://github.com/uiwjs/react-baidu-map/issues/194
