### ISSUE TITLE
卫星地图有使用示例嘛？

### ISSUE THREAD

**Issue by zemelLeong** [uiwjs/react-baidu-map#239]

**Comment by jaywcjlove** [comment]
https://uiwjs.github.io/react-baidu-map/#/map-type-control

@zemelLeong 你看这个适合你不？不行直接调用高德原生API。

**Comment by zemelLeong** [comment]
这个我理解只是通过按钮切换吧？我想自定义控制逻辑，我用的是百度地图

**Comment by zemelLeong** [comment]
```jsx
      <Map
        zoom={18}
        enableScrollWheelZoom
        enableDragging
        mapType="B_SATELLITE_MAP"
      >
        {children}
      </Map>
```
瞎搞搞出来了，但是`B_SATELLITE_MAP`这个量没在项目里被提及啊

**Comment by jaywcjlove** [comment]
@zemelLeong 欢迎提交 PR 更新文档。

**Comment by zemelLeong** [comment]
先忙过这一阵子
我不知道是什么原因，我之前用官方原生的js在地图上绘制多边形，有上千个，缩放还比较流畅，用这个库似乎会比较卡
