### ISSUE TITLE
hooks方式使用map，自定义样式 mapStyleV2 报错 "cross-origin error"

### ISSUE THREAD

**Issue by xiyangranhongyan** [uiwjs/react-baidu-map#253]
> 样式json 在组件方式使用时正常，另外百度官方的 json url 同样报错.

```
A cross-origin error was thrown. React doesn't have access to the actual error object in development.
```

## 使用方式 - 全报错

1. local json
2. js 变量
3. oss json
4. map.setMapStyleV2({ styleJson });

## 复现demo: https://codesandbox.io/s/modern-butterfly-crvlcn?file=/src/App.js

![报错及代码截图](https://images.gitee.com/uploads/images/2022/0301/181318_b9f6c996_5052254.png "屏幕截图.png")

**Comment by jaywcjlove** [comment]
https://codesandbox.io/s/eager-nightingale-4inotu?file=/src/App.js 
这个示例不知道怎么建的感觉有问题，跟组件没有关系吧 @Feafortecsy 

![image](https://user-images.githubusercontent.com/1680273/156279047-d6ec3b33-4b4d-4a35-92a0-b5920025ed4d.png)


我这个示例里面 JS 引入 没有 加 `crossorigin`，上面示例都加了这个，这个是 codesandbox 的问题吧
https://codesandbox.io/s/uiwjs-react-md-editor-issues-351-ep1qb0?file=/index.html

![image](https://user-images.githubusercontent.com/1680273/156279601-976eb30d-5900-4042-a255-347dcc7974a2.png)

**Comment by Feafortecsy** [comment]
@jaywcjlove fork了你的这个示例，但是自定义样式也没有生效，暂时找不到原因。我这边先跳过了，回头有时间再看

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-baidu-map/blob/de7213ea71fff7c07688d2bbc219d49522647d40/packages/map/README.md?plain=1#L107-L168

@Feafortecsy Hook 的新玩儿法。

**Comment by Feafortecsy** [comment]
@jaywcjlove 大佬牛逼。不过今天上线，测试已经测过了，还是稳妥为上，不然测试得打我，等下次迭代我再看看。
