### ISSUE TITLE
CustomOverlay 不支持批量渲染吗？

### ISSUE THREAD

**Issue by lijie0214** [uiwjs/react-baidu-map#254]
使用map 遍历数组渲染多个CustomOverlay时，地图上不显示

const overlays = [
  {
    lng: 117.46,
    lat: 39.94
  },
  {
    lng: 116.46,
    lat: 39.95
  },
  {
    lng: 116.46,
    lat: 39.93
  }
]

{
          overlays.map((item) => {
            return (
              <CustomOverlay position={ item } visiable={ true }>
                <div className={ styles.avatarWrapper }>
                  <div className={ styles.avatar }>
                    <img
                      className={ styles.avatarImg }
                      src={ defaultAvatar } alt=""
                    />
                  </div>
                </div>
              </CustomOverlay>
            )
          })
        }

**Comment by jaywcjlove** [comment]
@lijie0214 你可以使用 https://codesandbox.io/ 提供一个实例我帮你看看

**Comment by lijie0214** [comment]
> @lijie0214 你可以使用 https://codesandbox.io/ 提供一个实例我帮你看看

https://codesandbox.io/s/infallible-marco-b7nfii 麻烦帮忙看下，感谢

**Comment by jaywcjlove** [comment]
@lijie0214 将地图移动到北京就有你的 自定义的内容了

**Comment by lijie0214** [comment]
> @lijie0214 将地图移动到北京就有你的 自定义的内容了
好 可以了 谢谢～
