### ISSUE TITLE
umi build 时打包失败

### ISSUE THREAD

**Issue by shguanbin** [uiwjs/react-baidu-map#265]
close-锁版本

**Comment by jaywcjlove** [comment]
你可以使用 https://codesandbox.io 给我提供一个实例。不太清楚你怎么写的

在 CI 中打包是没有问题的。https://github.com/uiwjs/react-baidu-map/runs/5408172534?check_suite_focus=true

**Comment by shguanbin** [comment]
编译的时候没问题，主要是umi build 打包的时候出的问题。
<img width="982" alt="image" src="https://user-images.githubusercontent.com/22384999/162566926-b42d2063-6b35-46ee-8ba0-850e429894ab.png">
<img width="491" alt="image" src="https://user-images.githubusercontent.com/22384999/162566937-6e3f9654-a709-4157-b249-8c5e2be33123.png">

**Comment by jaywcjlove** [comment]
@shguanbin 提供实例，我帮你看看

**Comment by shguanbin** [comment]
@jaywcjlove 在gitlab-ci中报的错，本地编译和打包都ok的。

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/162572634-d4afb767-5326-4b92-9d5e-fdf970b1bf05.png)


@shguanbin 我这个 GitHub CI 中没有问题，我调试不了你的问题

**Comment by shguanbin** [comment]
@jaywcjlove 帮忙看下package.json 有问题不 

"dependencies": {
    "@antv/g2": "^4.1.31",
    "@uiw/react-baidu-map": "^2.0.5",
    "mockjs": "^1.1.0",
    "react": "^17.0.2",
    "react-dom": "17.x",
    "react-sticky": "^6.0.3"
  },
  "devDependencies": {
    "workbox-webpack-plugin": "6.5.1",
    "antd-dayjs-webpack-plugin": "^1.0.6",
    "caniuse-lite": "^1.0.30001313",
    "browserslist": "^4.19.3",
    "@umijs/plugin-antd": "^0.15.0",
    "@sentry/react": "^6.17.6",
    "@sentry/tracing": "^6.17.6",
    "@testing-library/react": "^11.2.6",
    "@types/express": "^4.17.11",
    "@types/jest": "^26.0.23",
    "@types/lodash": "^4.14.178",
    "@types/mockjs": "^1.0.3",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-sticky": "^6.0.4",
    "@umijs/fabric": "^2.5.10",
    "@umijs/plugin-crossorigin": "^1.2.1",
    "@umijs/plugin-esbuild": "^1.3.1",
    "@umijs/plugin-helmet": "1.1.3",
    "@umijs/test": "3.4.14",
    "babel-loader": "^8.2.2",
    "babel-plugin-import": "^1.13.3",
    "lint-staged": "^10.0.7",
    "prettier": "^2.2.0",
    "typescript": "4.5.4",
    "umi": "^3.4.14",
    "yorkie": "^2.0.0"
  }

**Comment by jaywcjlove** [comment]
看不了，没有那么神，你尝试锁定依赖看一下  ~~`"^17.0.0"`~~ - > `"17.0.0",`

@shguanbin

**Comment by jaywcjlove** [comment]
还有一个你 react  类型 依赖是不是版本有问题？

`"@types/react": "^17.0.0"` ->  `[17.0.39](https://www.npmjs.com/package/@types/react/v/17.0.39)` 最新的都 `17.0.39`

你可以升级试一试 @shguanbin

**Comment by shguanbin** [comment]
嗯，锁了版本也不行，4月6号之前都是好的，后面再编译就不行了。

**Comment by shguanbin** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/22384999/162576139-ea67bbac-34a5-4dcb-a975-5a1a50cfd1c5.png">
@jaywcjlove 和umijs版本会不会有关系

**Comment by jaywcjlove** [comment]
@shguanbin 你自己测试，不要升级到 18， 人家 umi types 集成了 `@types/react@16.14.24`。

18 的类型包对应的是 react 18

**Comment by shguanbin** [comment]
是React.ReactNode,这是最小的
![Uploading image.png…]()

**Comment by iizhan** [comment]
@jaywcjlove 同问，我也遇到了。重新install之后就出问题了，不好传实列，能加你Q来帮忙看下么。
@shguanbin 处理了麻烦告诉我下！

**Comment by jaywcjlove** [comment]
@shguanbin 图破了。

**Comment by shguanbin** [comment]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/22384999/162598467-820cf141-c8be-40db-99d8-d038aa53acbb.png">
@iizhan 嗯，还在处理，目前排查是两个类型不一致，现在在看编译过程。包括umi build 过程。

**Comment by shguanbin** [comment]
@jaywcjlove 
<img width="773" alt="image" src="https://user-images.githubusercontent.com/22384999/162598499-4e881595-93bc-4aa4-9d3c-3f8b69473194.png">
@iizhan 嗯，已经在处理了，有后续我同步下。目前在排查打包过程。

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-baidu-map/blob/f00e0b90eb6fc18622db83acb3e575b732d391da/tsconfig.json#L17

TypeScript 配置你也瞅一瞅，排查一下，之前 `jsx` 配置 `react`  升级之后 `react-jsx`

这个你确认一下 TypeScript 版本排查一下

@jaywcjlove

**Comment by shguanbin** [comment]
对的，我项目里面配的是的 "jsx": "react-jsx",
@jaywcjlove

**Comment by iizhan** [comment]
我的也是"jsx": "react-jsx" ，我看react-baidu-map 源码里配置的是jsx：react
@jaywcjlove @shguanbin

**Comment by iizhan** [comment]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/63840516/162599647-d4f4884b-4647-4da3-8583-3da53be4d9e9.png">
@jaywcjlove @shguanbin 会不会这个要升级换下？

**Comment by jaywcjlove** [comment]
@shguanbin 我不知道，我没有测试环境，你去看一下 typescript 文档，根据你自己的版本来配置吧

**Comment by iizhan** [comment]
@jaywcjlove [react-baidu-map](https://github.com/uiwjs/react-baidu-map) 插件里面用的是jsx:react这个不要紧么？
<img width="893" alt="image" src="https://user-images.githubusercontent.com/63840516/162599989-81e0f623-4af0-4f55-b546-5ba09074f1a2.png">

**Comment by shguanbin** [comment]
@iizhan 我小伙伴锁了版本就好了。。。我之前锁版本不行。
