### ISSUE TITLE
我传入坐标绘制线形 但是线不出来。。。。。。。

### ISSUE THREAD

**Issue by KyrieZhangi** [uiwjs/react-baidu-map#294]
![image](https://user-images.githubusercontent.com/106070280/226789827-6e7f72d7-84b0-469f-9da0-6bb3cf7e54fa.png)
数据有接收到，但是视图没有更新

**Comment by KyrieZhangi** [comment]
> @KyrieZhangi 你都是使用 `withMap` 拿到 map 对象，基于 map 对象操作，这已经跟组件没有关系了
> 
> 我们这个组件只是个壳子，你现在已经全部基于 map 原生 API 写了，所以你如果想让我帮你看代码，你得给我调试的环境，我可以帮你看看

@jaywcjlove 可以有空向日葵看下吗？ 不然实际的情形不好模拟

**Comment by KyrieZhangi** [comment]
932947630 8wr8z0

**Comment by jaywcjlove** [comment]
@KyrieZhangi 我对帮你修复 bug 没有兴趣，这不是组件 bug 的内容，你可以提供 https://codesandbox.io/ 示例给我我帮你看看

如果代理加载不出来，在应用加载之后代理关闭地图就可以加载出来了。
