### ISSUE TITLE
ref获取DrawingManager组件实例报错

### ISSUE THREAD

**Issue by liuaoin** [uiwjs/react-baidu-map#300]
![image](https://github.com/uiwjs/react-baidu-map/assets/38316934/12ae71b3-92ef-45da-8c74-a76c764ffdf2)

**Comment by jaywcjlove** [comment]
@liuaoin 不知道示例是如何写的，组件自己内部加载了 SDK，可能SDK不匹配

https://github.com/uiwjs/react-baidu-map/blob/8b3602aecb1efe020ca7f9601da9c4b3d1851b29/packages/drawing-manager/src/useDrawingManager.tsx#L50-L77

**Comment by liuaoin** [comment]
![image](https://github.com/uiwjs/react-baidu-map/assets/38316934/6d9346e2-bdbe-4b4f-964d-5da323b4f68a)

![image](https://github.com/uiwjs/react-baidu-map/assets/38316934/ab4aca48-6f78-428d-9dc2-491ef6074563)

**Comment by liuaoin** [comment]
![image](https://github.com/uiwjs/react-baidu-map/assets/38316934/1d9bc10e-6d59-4fec-8e14-b863e01ae321)

**Comment by jaywcjlove** [comment]
@liuaoin 你更新 `2.6.1` 试一试

**Comment by liuaoin** [comment]
已修复，感谢
