### ISSUE TITLE
Uncaught ReferenceError: BMAP_DRAWING_POLYGON is not defined

### ISSUE THREAD

**Issue by sunny-token** [uiwjs/react-baidu-map#320]
引入了    "@uiw/react-baidu-map-types": "^2.6.2",
在使用的地方报错了：Uncaught ReferenceError: BMAP_DRAWING_POLYGON is not defined
是需要引入什么文件吗？
```
const { drawingManager } = useDrawingManager({
		map,
		isOpen: false,
		enableDrawingTool: true,
		rectangleOptions: styleOptions,
		polygonOptions: styleOptions,
		drawingToolOptions: {
			anchor: BMAP_ANCHOR_TOP_RIGHT, drawingModes: [
				BMAP_DRAWING_POLYGON,
				BMAP_DRAWING_RECTANGLE
			]
		}
	})
```

**Comment by sunny-token** [comment]
@jaywcjlove 这是在线示例，麻烦帮忙排查一下哈，谢谢！` https://codesandbox.io/p/sandbox/xenodochial-mayer-nwkszf?file=%2Fsrc%2FDemo.js%3A36%2C66&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clplx8cj300063b6ib3pq45xl%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clplx8cj300023b6itcdwaspm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clplx8cj300033b6i4xer4kbr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clplx8cj300053b6i6qrdcqrz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clplx8cj300023b6itcdwaspm%2522%253A%257B%2522id%2522%253A%2522clplx8cj300023b6itcdwaspm%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clply2dca00023b6iv00ewwdk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clply7jy100023b6i5biq77zg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A36%252C%2522startColumn%2522%253A66%252C%2522endLineNumber%2522%253A36%252C%2522endColumn%2522%253A66%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clply7jy100023b6i5biq77zg%2522%257D%252C%2522clplx8cj300053b6i6qrdcqrz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clplx8cj300043b6ik3c6l1n3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clplx8cj300053b6i6qrdcqrz%2522%252C%2522activeTabId%2522%253A%2522clplx8cj300043b6ik3c6l1n3%2522%257D%252C%2522clplx8cj300033b6i4xer4kbr%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clplx8cj300033b6i4xer4kbr%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D`

**Comment by jaywcjlove** [comment]
@sunny-token 我查看示例并没有报错

<img width="1414" alt="image" src="https://github.com/uiwjs/react-baidu-map/assets/1680273/b4c403ab-a961-4ded-908f-4cead51e6160">

并且我查看了 对象是存在的

<img width="310" alt="image" src="https://github.com/uiwjs/react-baidu-map/assets/1680273/f1c5f6ac-78b0-4200-8d6a-cf56f255dfe0">

所以你参考我搞的 高德地图 https://github.com/uiwjs/react-amap/issues/45#issuecomment-759174172 来解决你的问题

造成这个原因只有 3 种，

1. 百度的 SDK 加载失败，对象 BMAP_DRAWING_POLYGON 没有挂在到全局对象
2. 遇到过，有一种开发环境必须 `window.BMAP_ANCHOR_TOP_LEFT` 去使用
3. 你在使用 `<APILoader>` （该组件用于加载 SDK）组件之前，使用了 `BMAP_ANCHOR_TOP_LEFT`

因为你的示例没有报错，我也无法找出问题，你可以提供可以重现的示例

**Comment by sunny-token** [comment]
@jaywcjlove  示例好像少点东西
```
drawingToolOptions: {
      anchor: BMAP_ANCHOR_TOP_RIGHT, // 位置
      offset: new BMap.Size(5, 5), // 偏离值
      drawingModes: [BMAP_DRAWING_POLYGON, BMAP_DRAWING_RECTANGLE],
    },
```

**Comment by jaywcjlove** [comment]
@sunny-token https://codesandbox.io/p/sandbox/lucid-joji-xp6q2t?file=%2Fsrc%2FDemo.js%3A38%2C16

这个就是我说的上面的第 `2` 点

**Comment by sunny-token** [comment]
@jaywcjlove  好的，谢谢！
问题解决了，需要使用挂载window下面的常量
```
drawingToolOptions: {
			anchor: window.BMAP_ANCHOR_TOP_RIGHT, drawingModes: [
				window.BMAP_DRAWING_POLYGON,
				window.BMAP_DRAWING_RECTANGLE
			]
		}
```
