### ISSUE TITLE
react-baidu-map-drawing-manager 如何监听切换绘制模式？

### ISSUE THREAD

**Issue by sunny-token** [uiwjs/react-baidu-map#321]
请问，我想在切换绘制模式的时候触发一些事件，我要怎么监听呢？
[代码示例](https://codesandbox.io/p/sandbox/xenodochial-mayer-nwkszf?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clplx8cj300063b6ib3pq45xl%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clplx8cj300023b6itcdwaspm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clplx8cj300033b6i4xer4kbr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clplx8cj300053b6i6qrdcqrz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clplx8cj300023b6itcdwaspm%2522%253A%257B%2522id%2522%253A%2522clplx8cj300023b6itcdwaspm%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clply2dca00023b6iv00ewwdk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clply7jy100023b6i5biq77zg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A36%252C%2522startColumn%2522%253A66%252C%2522endLineNumber%2522%253A36%252C%2522endColumn%2522%253A66%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clply7jy100023b6i5biq77zg%2522%257D%252C%2522clplx8cj300053b6i6qrdcqrz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clplx8cj300043b6ik3c6l1n3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clplx8cj300053b6i6qrdcqrz%2522%252C%2522activeTabId%2522%253A%2522clplx8cj300043b6ik3c6l1n3%2522%257D%252C%2522clplx8cj300033b6i4xer4kbr%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clplx8cj300033b6i4xer4kbr%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by jaywcjlove** [comment]
@sunny-token 看官方文档 API  https://api.map.baidu.com/library/DrawingManager/1.4/docs/symbols/BMapLib.DrawingManager.html

**Comment by sunny-token** [comment]
@jaywcjlove 文档没有的监听事件是不是就是不支持呢？我看文档也没有监听切换绘制模式的方法嘛，只有绘制完毕的监听

**Comment by jaywcjlove** [comment]
@sunny-token 更新到 `v2.7.0` 就提供了官方的事件，其实你可以通过 ref 获得 `drawingManager` 对象，自己监听事件
