### ISSUE TITLE
使用useMarker后发现后台一直在刷警告

### ISSUE THREAD

**Issue by sunny-token** [uiwjs/react-baidu-map#322]
const icon = new BMap.Icon('http://developer.baidu.com/map/jsdemo/img/fox.gif', new BMap.Size(300, 157));
useMarker({ map, position: NJ, icon: icon });
不使用icon没问题，使用了icon后，后台一直刷warring，麻烦看下是啥问题呢？
<img width="479" alt="image" src="https://github.com/uiwjs/react-baidu-map/assets/19677491/559cc0e9-24f9-4ab8-bfd8-9338720bb49a">
具体例子下面链接。
[demo](https://codesandbox.io/p/devbox/uiwjs-react-baidu-map-issues-267-usemarker-forked-cg8wnj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrq0z2jv00063b6h8yb9rhgv%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrq0z2ju00023b6hrfsebg59%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrq0z2ju00043b6hgbi9kcwz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrq0z2ju00053b6hy0lparrg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrq0z2ju00023b6hrfsebg59%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrq0z2ju00013b6hr2ujj8hf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrq0z2ju00023b6hrfsebg59%2522%252C%2522activeTabId%2522%253A%2522clrq0z2ju00013b6hr2ujj8hf%2522%257D%252C%2522clrq0z2ju00053b6hy0lparrg%2522%253A%257B%2522id%2522%253A%2522clrq0z2ju00053b6hy0lparrg%2522%252C%2522activeTabId%2522%253A%2522clrq1485x00r63b6ho2uqeq64%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clrq1485x00r63b6ho2uqeq64%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clrq0z2ju00043b6hgbi9kcwz%2522%253A%257B%2522id%2522%253A%2522clrq0z2ju00043b6hgbi9kcwz%2522%252C%2522activeTabId%2522%253A%2522clrq147sd00pk3b6hnr88ttgb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrq109dr00563b6hhrzhgc8o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrq10b8d000oehhnc1dndaab%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clrq147sd00pk3b6hnr88ttgb%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by sunny-token** [comment]
@jaywcjlove 好像用了icon后会导致副作用一直在刷，能帮忙看下吗？

**Comment by jaywcjlove** [comment]
@sunny-token 如果你提供可以重现错误的示例，我可以帮你看看

**Comment by sunny-token** [comment]
我上面的demo链接就是例子哦，你帮忙看看呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月23日(周二) 晚上7:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [uiwjs/react-baidu-map] 使用useMarker后发现后台一直在刷警告 (Issue #322)




 
@sunny-token 如果你提供可以重现错误的示例，我可以帮你看看

**Comment by jaywcjlove** [comment]
@sunny-token 使用 `useMemo` 可以解决这个问题

```js
const  icon = useMemo(() => {
    return new BMap.Icon(
      "http://developer.baidu.com/map/jsdemo/img/fox.gif",
      new BMap.Size(300, 157),
    );
}, [])
```

**Comment by sunny-token** [comment]
好的，我试试，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月23日(周二) 晚上8:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [uiwjs/react-baidu-map] 使用useMarker后发现后台一直在刷警告 (Issue #322)




 
@sunny-token 使用 useMemo 可以解决这个问题
 const  icon = useMemo(() =&gt; {     return new BMap.Icon(       "http://developer.baidu.com/map/jsdemo/img/fox.gif",       new BMap.Size(300, 157),     ); }, [])

**Comment by sunny-token** [comment]
可以了，用usememo解决了
