### ISSUE TITLE
csp导致Failed to load Baidu Map: The Script http://api.map.baidu.com/api?v=2.0&ak=xxx&callback=load_bmap_sdk is no accessible.

### ISSUE THREAD

**Issue by jy1989** [uiwjs/react-baidu-map#326]
请问有解决方案吗？

![image](https://github.com/uiwjs/react-baidu-map/assets/1291756/ac072d80-701b-4ef9-b7cc-198b077a0398)

**Comment by jaywcjlove** [comment]
@jy1989  这是什么安全策略？导致的？

**Comment by jy1989** [comment]
@jaywcjlove 上面截图是用谷歌浏览器版本 121.0.6167.189（正式版本），应是浏览器的安全策略。 我又用edge测试了一下  也是同样的错误：
![image](https://github.com/uiwjs/react-baidu-map/assets/1291756/9f012ac0-b064-41d5-8f52-7c840e909d25)

**Comment by jy1989** [comment]
貌似是我用的strapi框架的安全策略   应该和浏览器无关，我先研究下，谢谢  @jaywcjlove
