### ISSUE TITLE
如何将GroundOverlay放到地图的底层

### ISSUE THREAD

**Issue by zswcat** [uiwjs/react-baidu-map#335]
目前看GroundOverlay是在折线、marker这些上层的，如何改到底层，目前看没有暴露方法出来。求问

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-baidu-map/blob/3f01e8e792cd4b9dd3dcaf132c8932d14926f558/packages/curve-line/src/index.tsx#L15-L21

通过 ref 或者 hook 拿到底层对象 @zswcat

**Comment by zswcat** [comment]
感谢大佬的回复，我还是有一些疑问

我参照官方样例使用的ref，代码如下
``` jsx
const BackUtilDisplay = (props: { imageBackg: ImageBackg }) => {
    const { imageBackg } = props

    const groundRef = (props: any) => {
        if (props && props.groundOverlay) {
            console.log('groundOverlay:', props.groundOverlay);
        }
    }

    return (
        /** @ts-ignore */
        <GroundOverlay bounds={new BMap.Bounds(imageBackg.sw, imageBackg.ne)} imageURL={imageBackg.src}
            ref={groundRef}
            opacity={imageBackg.opacity}
            displayOnMinLevel={4}
            displayOnMaxLevel={9}
        />
    )
}
```
前端打印到的数据如下
<img width="373" alt="image" src="https://github.com/user-attachments/assets/7b4e1521-571d-4bac-91f9-8cfe5cd2fbc0">
求问我应该如何改层级

**Comment by jaywcjlove** [comment]
@zswcat  map 实例对象不是拿到了，你想咋改就咋改哦

**Comment by zswcat** [comment]
> @zswcat map 实例对象不是拿到了，你想咋改就咋改哦

大佬，我是个前端小白，试了map里边的各种东西，感觉都不生效。可以帮忙详细给讲解下吗。付费咨询也可以，感谢～

**Comment by zswcat** [comment]
> > @zswcat map 实例对象不是拿到了，你想咋改就咋改哦
> 
> 我通过里边ca拿到了div，改了zIndex，丑陋的实现了。但是有个问题，是必须点击一次地图，才会生效

已经解决，加了个延迟500ms

**Comment by zswcat** [comment]
> 目前看GroundOverlay是在折线、marker这些上层的，如何改到底层，目前看没有暴露方法出来。求问
