### ISSUE TITLE
非常感谢作者的付出

### ISSUE THREAD

**Issue by world56** [uiwjs/react-baidu-map#4]
这么优秀的组件库咋没人star，我主要是过来👍一波！

**Comment by world56** [comment]
请问 Map组件内 d.ts为啥没定义onClick事件啊？

**Comment by jaywcjlove** [comment]
@world56 更新 `+ @uiw/react-baidu-map@1.14.1`， Bug修复了。

**Comment by jaywcjlove** [comment]
@world56 刚撸出来的，懒得推广，主要是自用。

**Comment by world56** [comment]
牛逼，这么快，谢谢撸主。

**Comment by jaywcjlove** [comment]
@world56 简单问题，不费神。
