### ISSUE TITLE
Marker组件 typescript环境接口定义问题

### ISSUE THREAD

**Issue by world56** [uiwjs/react-baidu-map#5]
```
     <APILoader akay={MAP_KEY}>
                <Map widget={['NavigationControl']} zoom={13}>
                    <Marker position={{ lng: 121.465145, lat: 31.241247 }} />
                </Map>
            </APILoader>
```
必填 设置标注的地理坐标。

Property 'equals' is missing in type '{ lng: number; lat: number; }' but required in type 'Point'.ts(2741)
base.d.ts(26, 5): 'equals' is declared here.
index.d.ts(8, 5): The expected type comes from property 'position' which is declared here on type 'IntrinsicAttributes & MarkerProps & RefAttributes<MarkerProps & { marker?: Marker | undefined; }>'

**Comment by world56** [comment]
字段position如上设置 则 typescript提醒该错误

**Comment by jaywcjlove** [comment]
@world56 错误已经修复 `+ @uiw/react-baidu-map@1.15.1`
