### ISSUE TITLE
mapStyleV2 Prop 设置Type问题

### ISSUE THREAD

**Issue by chachaxw** [uiwjs/react-baidu-map#8]
用下面方式无法设置mapStyleV2属性，我看文档上写的有这个属性，是我用错了吗？
```jsx
<Map zoom={18} enableScrollWheelZoom center={path.length > 0 ? path[0] : ''} mapStyleV2={}>
     <Polyline path={path} strokeColor="#07bd13" />
     <Polyline path={path.filter((item: any) => item.crossed)} strokeColor="#ff5f58" />
</Map>
```

**Comment by jaywcjlove** [comment]
@chachaxw 实例：https://codesandbox.io/s/react-baidu-map-example-pjczp

`center` 属性设置错误

**Comment by chachaxw** [comment]
@jaywcjlove 我这边center设置没错，我的path是一个 {lat: number, lag: number} 的数据，我这边用的是typescript，那个报的是类型错误，提示Map组件没有mapStyleV2属性

**Comment by jaywcjlove** [comment]
@chachaxw 已修复 `+ @uiw/react-baidu-map@1.15.4`

**Comment by chachaxw** [comment]
@jaywcjlove 设置mapStyleV2 属性为 `mapStyleV2={{ styleJson }}` 报错

**Comment by jaywcjlove** [comment]
@chachaxw 请给出实例

**Comment by chachaxw** [comment]
@jaywcjlove 就是设置地图主题的时候, styleJson 是从百度地图下载的json文件 [http://lbsyun.baidu.com/apiconsole/custommap](百度地图自定义)
通过styleId 或者 styleJson都无法正常设置地图样式，出现页面崩溃，应该地图组件Map的问题
```
<Map zoom={18} enableScrollWheelZoom center={path.length > 0 ? path[0] : ''} mapStyleV2={{ styleJson }}>
     <Polyline path={path} strokeColor="#07bd13" />
     <Polyline path={path.filter((item: any) => item.crossed)} strokeColor="#ff5f58" />
</Map>
```

**Comment by chachaxw** [comment]
@jaywcjlove 大佬，有没有什么开源项目可以贡献代码的？

**Comment by jaywcjlove** [comment]
@chachaxw 可以用 https://codesandbox.io 建个实例。

你可以在排行榜上选择热门你感兴趣的项目贡献代码 http://jaywcjlove.github.io/github-rank/repos.html 

你也可以根据自己的需求撸自己的工程，百度地图 react 包就是项目中用到的封装的。

**Comment by jaywcjlove** [comment]
@chachaxw 你也可以解决你使用百度地图出现的类型问题，提交PR 来贡献这个仓库。

比如一些人使用我的 https://github.com/jaywcjlove/mocker-api 这个包，对它做了不少贡献。这些贡献都是解决平时使用的相关问题。

**Comment by chachaxw** [comment]
@jaywcjlove 感谢大佬指教

**Comment by chachaxw** [comment]
@jaywcjlove https://codesandbox.io/s/competent-satoshi-hn8ti
通过styleId 或者 styleJson都无法正常设置地图样式，出现页面崩溃，可以看console里面的报错

**Comment by jaywcjlove** [comment]
@chachaxw  https://codesandbox.io/s/react-baidu-map-example-pjczp 不是实例发给你了

**Comment by jaywcjlove** [comment]
> @jaywcjlove https://codesandbox.io/s/competent-satoshi-hn8ti
> 通过styleId 或者 styleJson都无法正常设置地图样式，出现页面崩溃，可以看console里面的报错

你的实例缺少 `center` 参数才会报哪个错误

**Comment by chachaxw** [comment]
@jaywcjlove 了解了大佬，感谢🙏
