### ISSUE TITLE
跑开发环境报错

### ISSUE THREAD

**Issue by liaoyinglong** [uiwjs/react-baidu-map#84]
![image](https://user-images.githubusercontent.com/23382699/104033444-7f127a00-520a-11eb-8b9d-cb6211b7a41f.png)

步骤：
1. git clone 
2. yarn 
3. yarn watch 
4. yarn start

**Comment by jaywcjlove** [comment]
@liaoyinglong 组件和网站是分开的， `src`目录是组件，`website` 是文档网站 运行的时候需要先 build 一下 `npm run build`

1. clone
2. yarn install
3. yarn run build
4. yarn run watch
5. yarn start

**Comment by liaoyinglong** [comment]
还是不行，同样的报错

我是`windows`环境


debug到`node_modules/react-dev-utils/WebpackDevServerUtils.js`
![image](https://user-images.githubusercontent.com/23382699/104085888-d0b01880-528d-11eb-87a2-c814f9c9fbe4.png)

编译入口并不是`website`


`react-script/config/webpack.config.js`里面的入口也并不是`paths.appSrc` 而是`paths.appIndexJs`


![image](https://user-images.githubusercontent.com/23382699/104085951-60ee5d80-528e-11eb-913d-8610bb3eae95.png)

**Comment by jaywcjlove** [comment]
@liaoyinglong 我猜可能是 kkt 这个工具出了兼容问题，不知道能否帮忙测试一下

kkt 这个工具是基于 [`create-react-app`](https://github.com/facebook/create-react-app) 重构了一下，但是我在 windows 上并没有测试



[@kkt/core/src/overrides/paths.ts](https://github.com/kktjs/kkt/blob/30d0448569e82dcdd096d74dea5b0db8e805afd6/core/src/overrides/paths.ts#L41-L49)


```ts
  if (argvs && argvs['app-src']) {
    const oldAppSrc = pathsConf.appSrc;
    pathsConf.appSrc = path.resolve(pathsConf.appPath, argvs['app-src']);
    Object.keys(pathsConf).forEach((keyname) => {
      if ((new RegExp(`^${oldAppSrc}`)).test(pathsConf[keyname])) {
        pathsConf[keyname] = pathsConf[keyname].replace(new RegExp(`^${oldAppSrc}`), pathsConf.appSrc);
      }
    });
  }
```

原理很简单，就是 node.js  加载包之后，通过替换缓存内容，改变原来包里面的内容

在下面两个地方帮我打个日志，没有 windows  系统短时间没有办法解决

```diff
  if (argvs && argvs['app-src']) {
    const oldAppSrc = pathsConf.appSrc;
+    console.log('->', oldAppSrc)
    pathsConf.appSrc = path.resolve(pathsConf.appPath, argvs['app-src']);
    Object.keys(pathsConf).forEach((keyname) => {
+    console.log('->', pathsConf[keyname])
      if ((new RegExp(`^${oldAppSrc}`)).test(pathsConf[keyname])) {
        pathsConf[keyname] = pathsConf[keyname].replace(new RegExp(`^${oldAppSrc}`), pathsConf.appSrc);
      }
    });
  }
```

我想可能是windows 获取路径 `\\` 和 macOS上的`/` 发生了兼容问题，导致 `oldAppSrc` 并没有命中缓存中的内容。

**Comment by liaoyinglong** [comment]
log

![image](https://user-images.githubusercontent.com/23382699/104087433-a57ff600-529a-11eb-8e78-d43f527d8b49.png)



这个是 pathsConf
![image](https://user-images.githubusercontent.com/23382699/104087457-d2cca400-529a-11eb-9fbe-2e5cc0839894.png)

**Comment by liaoyinglong** [comment]
![image](https://user-images.githubusercontent.com/23382699/104087567-a2d1d080-529b-11eb-887c-77f284e26665.png)

是这里

**Comment by jaywcjlove** [comment]
@liaoyinglong 能打印一下 `keyname ` 吗？

```
  if (argvs && argvs['app-src']) {
    const oldAppSrc = pathsConf.appSrc;
+    console.log('->', oldAppSrc)
    pathsConf.appSrc = path.resolve(pathsConf.appPath, argvs['app-src']);
    Object.keys(pathsConf).forEach((keyname) => {
+    console.log('->', keyname, pathsConf[keyname])
      if ((new RegExp(`^${oldAppSrc}`)).test(pathsConf[keyname])) {
        pathsConf[keyname] = pathsConf[keyname].replace(new RegExp(`^${oldAppSrc}`), pathsConf.appSrc);
      }
    });
  }
```

**Comment by jaywcjlove** [comment]
```js

      if ((new RegExp(`^${oldAppSrc}`)).test(pathsConf[keyname])) {
        pathsConf[keyname] = pathsConf[keyname].replace(new RegExp(`^${oldAppSrc}`), pathsConf.appSrc);
      }
```

那应该是这一句的问题了。匹配路径，进行替换路径的时候，没有匹配上。

**Comment by liaoyinglong** [comment]
> @liaoyinglong 能打印一下 `keyname ` 吗？
> 
> ```diff
>   if (argvs && argvs['app-src']) {
>     const oldAppSrc = pathsConf.appSrc;
> +    console.log('->', oldAppSrc)
>     pathsConf.appSrc = path.resolve(pathsConf.appPath, argvs['app-src']);
>     Object.keys(pathsConf).forEach((keyname) => {
> +    console.log('->', keyname, pathsConf[keyname])
>       if ((new RegExp(`^${oldAppSrc}`)).test(pathsConf[keyname])) {
>         pathsConf[keyname] = pathsConf[keyname].replace(new RegExp(`^${oldAppSrc}`), pathsConf.appSrc);
>       }
>     });
>   }
> ```

`keyname` 可以看  [这里的](https://github.com/uiwjs/react-baidu-map/issues/84#issuecomment-757118191) 的第二张图

**Comment by jaywcjlove** [comment]
@liaoyinglong 

![image](https://user-images.githubusercontent.com/1680273/104088069-28a34b00-529f-11eb-8f0b-439c38865b67.png)

我看了好些个并没有替换掉。 这个判断 `(new RegExp(`^${oldAppSrc}`)).test(pathsConf[keyname])` 是有问题的

或者是说 下面这句有问题。

```js
pathsConf[keyname] = pathsConf[keyname].replace(new RegExp(`^${oldAppSrc}`), pathsConf.appSrc);
``

**Comment by jaywcjlove** [comment]
@liaoyinglong 更新了依赖不知道是否有问题哦。

**Comment by jaywcjlove** [comment]
@liaoyinglong nice! 自动化 Windows 测试通过了。看上去没有问题的样子。


https://github.com/uiwjs/react-baidu-map/runs/1686283776?check_suite_focus=true
