### ISSUE TITLE
GeolocationResult 缺少 address 属性

### ISSUE THREAD

**Issue by amin168** [uiwjs/react-baidu-map#9]
如下图所示
![image](https://user-images.githubusercontent.com/10808093/76695567-0f039800-66bc-11ea-874e-6296e3553e9b.png)
![image](https://user-images.githubusercontent.com/10808093/76695570-22aefe80-66bc-11ea-87df-e1a244847353.png)

**Comment by jaywcjlove** [comment]
@amin168 添加缺失类型 3f63c77

**Comment by jaywcjlove** [comment]
@amin168 Upgrade `+ @uiw/react-baidu-map@1.15.5`
